module.exports = {
    theme: 'baddies',
    first: [
        'Axel',
        'Baron Von',
        'Bartholomew',
        'Benjamin',
        'Bethany',
        'Boris',
        'Caroline',
        'Chancelor',
        'Count',
        'Claude Von',
        'Clawdia',
        'Clawdine',
        'Cruella',
        'Demonica',
        'Dethanie',
        'Edgar',
        'Egor Von',
        'Eyegore',
        'Franklin',
        'Gregory',
        'Grindle',
        'Guillotina',
        'Harold',
        'Harriet',
        'Harry',
        'Igor',
        'James Von',
        'Jonathan',
        'Joseph',
        'Karen',
        'Killbert',
        'Killroy',
        'Madeline',
        'Malicetor',
        'Mallory',
        'Maude Von',
        'Monica',
        'Natalie',
        'Rachel',
        'Ramsey',
        'Rotbert',
        'Supreme Leader',
        'Snidely',
        'Wallace',
        'Wendy Von',
        'William',
    ],
    last: [
        'Angerton',
        'Barfstone',
        'Blackheart',
        'Blisterson',
        'Crabbington',
        'Crankerton',
        'Crankford',
        'Cruelheart',
        'Cruelmoore',
        'Deadmoore',
        'Deathstone',
        'Deville',
        'Dracula',
        'Dreadford',
        'Fearmoore',
        'Frankenstein',
        'Gravestone',
        'Greygore',
        'Greystone',
        'Gruesome',
        'Hatesmith',
        'Hatestone',
        'Hauntington',
        'Hauntstein',
        'Hellford',
        'Hellstone',
        'Horrorstone',
        'Hurtsmoore',
        'Killgore',
        'Killgrave',
        'Killjoy',
        'Killmoore',
        'Killruseau',
        'Malstone',
        'Nastiford',
        'Oddman',
        'Painsfield',
        'Painsford',
        'Rotbertson',
        'Rottenburough',
        'Rottenfoot',
        'Rottford',
        'Rotmoore',
        'Ruthlesson',
        'Saltmire',
        'Shankford',
        'Shankheart',
        'Shiftmoore',
        'Sinisterson',
        'Slaughterhouse',
        'Sliverton',
        'Snakefoot',
        'Splinterman',
        'Stabbington',
        'Swamperton',
        'Swampfoot',
        'Swampmire',
        'Terrorstone',
        'Voorhees',
        'Wickedon',
        'Whiplash',
    ],
};
